export const FEATURE_FLAGS = {
  ENABLE_AI: true,
  ENABLE_SHIPROCKET: true,
  ENABLE_VENDOR_SCORING: true,
  ENABLE_SUBSCRIPTIONS: true,
  ENABLE_NEGOTIATIONS: true,
  ENABLE_PORTAL: true,
  ENABLE_ANALYTICS: true,
  ENABLE_DEMO_TOUR: true,
  ENABLE_ROLE_SWITCHER: true,
};
