import { create } from 'zustand';
import { Company, CurrencyCode } from '../types/api';
import { User, UserRole } from '../types/auth';
import { ROLE_PERMISSIONS, ROLE_LABELS } from '../utils/permissions';

export const DEMO_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    name: 'Apex Enterprise Solutions Ltd',
    code: 'APEX',
    currency: 'INR',
    taxId: 'GSTIN24AAACA1234F1Z5',
    country: 'India',
  },
  {
    id: 'comp-2',
    name: 'Orbit Global Technologies Inc',
    code: 'ORBIT',
    currency: 'USD',
    taxId: 'US-EIN-987654321',
    country: 'United States',
  },
];

export const DEMO_USERS: Record<UserRole, User> = {
  ADMIN: {
    id: 'usr-admin',
    name: 'Jordan Davis',
    firstName: 'Jordan',
    lastName: 'Davis',
    email: 'jordan.davis@quoteflow.example',
    phone: '+91 98765 43210',
    jobTitle: 'System Administrator',
    department: 'Revenue Operations',
    team: 'revenue',
    location: 'Mumbai, India',
    memberSince: 'January 2023',
    status: 'ACTIVE',
    twoFactorEnabled: false,
    role: 'ADMIN',
    roleTitle: ROLE_LABELS.ADMIN,
    companyId: 'comp-1',
    permissions: ROLE_PERMISSIONS.ADMIN,
    preferences: {
      emailApprovals: true,
      emailCustomerActivity: true,
      emailBillingReminders: false,
      smsAlerts: true,
      weeklyDigest: true,
    },
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face',
  },
  SALES_MANAGER: {
    id: 'usr-sm',
    name: 'Vikram Mehta',
    firstName: 'Vikram',
    lastName: 'Mehta',
    email: 'vikram.m@quoteflow.example',
    phone: '+91 98234 56789',
    jobTitle: 'Sales Director',
    department: 'Sales',
    team: 'sales',
    location: 'Mumbai, India',
    memberSince: 'March 2023',
    status: 'ACTIVE',
    twoFactorEnabled: true,
    role: 'SALES_MANAGER',
    roleTitle: ROLE_LABELS.SALES_MANAGER,
    companyId: 'comp-1',
    permissions: ROLE_PERMISSIONS.SALES_MANAGER,
    preferences: {
      emailApprovals: true,
      emailCustomerActivity: true,
      emailBillingReminders: true,
      smsAlerts: false,
      weeklyDigest: true,
    },
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
  },
  SALES_REP: {
    id: 'usr-rep',
    name: 'Ananya Sharma',
    firstName: 'Ananya',
    lastName: 'Sharma',
    email: 'ananya.s@quoteflow.example',
    phone: '+91 98111 22334',
    jobTitle: 'Senior Account Executive',
    department: 'Sales',
    team: 'sales',
    location: 'Bengaluru, India',
    memberSince: 'August 2023',
    status: 'ACTIVE',
    twoFactorEnabled: false,
    role: 'SALES_REP',
    roleTitle: ROLE_LABELS.SALES_REP,
    companyId: 'comp-1',
    permissions: ROLE_PERMISSIONS.SALES_REP,
    preferences: {
      emailApprovals: true,
      emailCustomerActivity: true,
      emailBillingReminders: false,
    },
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face',
  },
  FINANCE: {
    id: 'usr-cfo',
    name: 'Rajesh Singhania',
    firstName: 'Rajesh',
    lastName: 'Singhania',
    email: 'rajesh.cfo@quoteflow.example',
    phone: '+91 98333 44556',
    jobTitle: 'Finance & Billing Director',
    department: 'Finance',
    team: 'finance',
    location: 'Delhi, India',
    memberSince: 'February 2022',
    status: 'ACTIVE',
    twoFactorEnabled: true,
    role: 'FINANCE',
    roleTitle: ROLE_LABELS.FINANCE,
    companyId: 'comp-1',
    permissions: ROLE_PERMISSIONS.FINANCE,
    preferences: {
      emailApprovals: true,
      emailCustomerActivity: false,
      emailBillingReminders: true,
    },
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
  },
  FINANCE_DIRECTOR: {
    id: 'usr-cfo',
    name: 'Rajesh Singhania',
    firstName: 'Rajesh',
    lastName: 'Singhania',
    email: 'rajesh.cfo@quoteflow.example',
    phone: '+91 98333 44556',
    jobTitle: 'Finance & Billing Director',
    department: 'Finance',
    team: 'finance',
    location: 'Delhi, India',
    memberSince: 'February 2022',
    status: 'ACTIVE',
    twoFactorEnabled: true,
    role: 'FINANCE_DIRECTOR',
    roleTitle: ROLE_LABELS.FINANCE_DIRECTOR,
    companyId: 'comp-1',
    permissions: ROLE_PERMISSIONS.FINANCE_DIRECTOR,
    preferences: {
      emailApprovals: true,
      emailCustomerActivity: false,
      emailBillingReminders: true,
    },
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
  },
  OPERATIONS: {
    id: 'usr-ops',
    name: 'Karan Patel',
    firstName: 'Karan',
    lastName: 'Patel',
    email: 'karan.ops@quoteflow.example',
    phone: '+91 98555 66778',
    jobTitle: 'Operations & Fulfillment Lead',
    department: 'Logistics',
    team: 'operations',
    location: 'Ahmedabad, India',
    memberSince: 'November 2023',
    status: 'ACTIVE',
    twoFactorEnabled: false,
    role: 'OPERATIONS',
    roleTitle: ROLE_LABELS.OPERATIONS,
    companyId: 'comp-1',
    permissions: ROLE_PERMISSIONS.OPERATIONS,
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
  },
  WAREHOUSE_MANAGER: {
    id: 'usr-wh',
    name: 'Karan Patel',
    firstName: 'Karan',
    lastName: 'Patel',
    email: 'karan.p@quoteflow.example',
    phone: '+91 98555 66778',
    jobTitle: 'Head of Inventory & Warehouses',
    department: 'Logistics',
    team: 'operations',
    location: 'Ahmedabad, India',
    memberSince: 'November 2023',
    status: 'ACTIVE',
    twoFactorEnabled: false,
    role: 'WAREHOUSE_MANAGER',
    roleTitle: ROLE_LABELS.WAREHOUSE_MANAGER,
    companyId: 'comp-1',
    permissions: ROLE_PERMISSIONS.WAREHOUSE_MANAGER,
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
  },
  PROCUREMENT_LEAD: {
    id: 'usr-proc',
    name: 'Devendra Joshi',
    firstName: 'Devendra',
    lastName: 'Joshi',
    email: 'devendra.j@quoteflow.example',
    phone: '+91 98777 88990',
    jobTitle: 'Procurement & Supply Specialist',
    department: 'Procurement',
    team: 'operations',
    location: 'Pune, India',
    memberSince: 'January 2024',
    status: 'ACTIVE',
    twoFactorEnabled: false,
    role: 'PROCUREMENT_LEAD',
    roleTitle: ROLE_LABELS.PROCUREMENT_LEAD,
    companyId: 'comp-1',
    permissions: ROLE_PERMISSIONS.PROCUREMENT_LEAD,
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&h=100&fit=crop&crop=face',
  },
  CUSTOMER: {
    id: 'usr-cust',
    name: 'Rohan Desai',
    firstName: 'Rohan',
    lastName: 'Desai',
    email: 'rohan.desai@quantumcloud.com',
    phone: '+1 (555) 234-5678',
    jobTitle: 'Chief Technology Officer',
    department: 'Engineering',
    team: 'client',
    location: 'San Francisco, USA',
    memberSince: 'May 2023',
    status: 'ACTIVE',
    twoFactorEnabled: true,
    role: 'CUSTOMER',
    roleTitle: ROLE_LABELS.CUSTOMER,
    companyId: 'comp-1',
    customerId: 'cust-1',
    permissions: ROLE_PERMISSIONS.CUSTOMER,
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop&crop=face',
  },
};

interface AuthState {
  user: User | null;
  company: Company;
  currency: CurrencyCode;
  isAuthenticated: boolean;
  isServerOnline: boolean;
  setUser: (user: User | null) => void;
  setCompany: (company: Company) => void;
  setCurrency: (currency: CurrencyCode) => void;
  setServerOnline: (online: boolean) => void;
  switchRole: (role: UserRole) => void;
  login: (user: User, token?: string) => void;
  logout: () => void;
}

export const useAuthStore = create<AuthState>((set) => ({
  user: null,
  company: DEMO_COMPANIES[0],
  currency: 'USD',
  isAuthenticated: false,
  isServerOnline: true,
  setUser: (user) => set({ user }),
  setCompany: (company) => set({ company, currency: company.currency }),
  setCurrency: (currency) => set({ currency }),
  setServerOnline: (isServerOnline) => set({ isServerOnline }),
  switchRole: (role: UserRole) => {
    const newUser = DEMO_USERS[role] || DEMO_USERS.ADMIN;
    set({ user: newUser });
  },
  login: (user, _token) => set({ user, isAuthenticated: true }),
  logout: () => set({ user: null, isAuthenticated: false }),
}));

